### PR TITLE
Add CENNZnet extrinsics

### PR DESCRIPTION
**Pull request by HiruSylo**
Add support for making signed transactions to the CENNZnet runtime.

### CODE REVIEW

**Comment by stwiname** [comment]
Everything looks fine. But we break compatibility with substrate. Do you think there's a way that we could define only new types and have a wrapper or extension library like how cennznet has done with the TS libs?

**Comment by HiruSylo** [comment]
> Everything looks fine. But we break compatibility with substrate. Do you think there's a way that we could define only new types and have a wrapper or extension library like how cennznet has done with the TS libs?

@stwiname From what I've tested so far, the CENNZnet TS API is unfortunately not compatible with a base substrate runtime.

One possibility is to have a boolean flag somewhere in the code which indicates whether this is being run on CENNZnet or not. Then at runtime, the boolean flag would determine how the extrinsic payload is encoded. This might require the use of a globally scoped variable (I think Go has those) to act as the boolean flag as the `Encode` function can only take in one input.

If we leave it as is, and Sylo switches from CENNZnet to a normal Substrate runtime, then I think we can [replace/patch](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive) the dependency to use the original upstream version of this library. Not quite sure how much change would be required as we don't really depend on any of the CENNZnet specific stuff currently.

**Comment by stwiname** [comment]
Ok, we can leave it as is for now. Can we update the readme and repo name to use cennznet rather than substrate please

**Comment by HiruSylo** [comment]
Will do. Should I also rename the actual go module name? I'm a bit hesitant to do so as it's much easier to patch the fork (which will cost 1 line of code per new project) than it is to rename all instances of that name throughout the code base of this repo.

**Comment by stwiname** [comment]
Lets leave it for now. We can always script it

**Pull request merged**
