### PR TITLE
Fix marshal and unmarshal of json hex strings into u128 and u256

### PR DESCRIPTION
**Pull request by HiruSylo**
This change is to allow the types that use the U128 and U256 types elsewhere in their code base to properly encode it to JSON and then decode it back again.

Previously, it would only encode the large numbers as hex strings but not decode them. This required users of the module to switch the types before/after interacting with the gcrpc which added extra boiler plate.

Edit: Also changes the endianess of the bytes to Big Endian when encoding/decoding as that's what the CENNZnet RPC uses.

### CODE REVIEW

**Comment by fishmonger45** [comment]
Thanks for this
Tests fail on my end. Not sure if related:
https://gist.github.com/wqsz7xn/2f462e6910ea711031f69064679e47dc

**Comment by HiruSylo** [comment]
> Thanks for this
> Tests fail on my end. Not sure if related:
> https://gist.github.com/wqsz7xn/2f462e6910ea711031f69064679e47dc

@wqsz7xn What are the steps you took to get this?

**Comment by fishmonger45** [comment]
Just ran `make test` @HiruSylo

**Comment by HiruSylo** [comment]
Do you have subkey installed and in your bash path?

**Comment by HiruSylo** [comment]
@wqsz7xn I've merged master into this branch which should bring in the subkey replacement.
Try pulling the latest of this branch and running your tests again.

**Comment by HiruSylo** [comment]
I've also changed the endianess of the encoding to big endian which is what the CENNZnet JSON RPC expects.

(Related to the bug @wqsz7xn found)

**Comment by fishmonger45** [comment]
Oops I have taken a bit long on this. I have moved some of the changes in this (just the json encoding/decoding w/o the endian fixes) to the branch `dealias`. I'm still getting failed tests though on this. A bit of a mess of a log. [log.txt](https://github.com/dn3010/go-cennznet-rpc-client/files/5928585/log.txt)

**Comment by stwiname** [comment]
@wqsz7xn are the tests failing on this branch or `dealais`? Is it possible to get some data that fails we can then put it in a test

**Comment by fishmonger45** [comment]
@stwiname 
Tests were for this branch.
Weird. I just purged chain and tests are working again.

**Comment by stwiname** [comment]
Could the data be different and not produce a failing test?

**Comment by HiruSylo** [comment]
All of the errors from that log seem to be
```
Error:      	timeout reached without getting 2 notifications from subscription
```

So what I think was happening was that your CENNZnet runtime was running but then you stopped it (or your pc went to sleep) and then resumed it after some time has passed.
CENNZnet requires the runtime to always be running or else it gets out of sync and starts producing an error about how the epoch has changed unexpectedly (this is just from my experience).
This error prevents new blocks from being created and so your tests waits for a long time for that extrinsic to be included in the next block and then eventually times out because it never happens.

**Pull request merged**
